modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Spawn/issues"

[[mods]]
    modId="project_essentials_spawn"
    version="${file.jarVersion}"
    displayName="Project Essentials Spawn"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Spawn/MC-1.15.2/updatev2.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Spawn"
    credits="hujle, KuroNoSeiHai, JetBrains, all forge developers, and other contributors"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    How we control spawn point! Adds literally two commands to configure
    players spawn point in the game world.
    '''

[[dependencies.projectessentialspermissions]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsspawn]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsspawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
