modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Spawn/issues"

[[mods]]
    modId="project_essentials_spawn"
    version="1.15.2-1.1.0"
    displayName="Project Essentials Spawn"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Spawn/MC-1.15.2/update.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Spawn"
    credits="Thanks JetBrains for Intellij IDEA license!"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Project Essentials Spawn - additional module for Essentials;
    Just controlling world spawn position for players.
    '''

[[dependencies.projectessentialspermissions]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsspawn]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsspawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
